version: "3.7"

networks:
  net-alice-kms:
  net-alice:
  net-bob:
  net-public:

services:

  kms-alice:
    command: start --config /root/tmkms/tmkms.toml -v
    container_name: kms-alice
    image: tmkms_i:v0.12.2
    networks:
      - net-alice-kms
    volumes:
      - ./kms-alice:/root/tmkms

  val-alice:
    command: start
    container_name: val-alice
    depends_on:
      - kms-alice
    image: fantasfived_i
    networks:
      - net-alice-kms
      - net-alice
    volumes:
      - ./val-alice:/root/.fantasfive

  sentry-alice:
    command: start
    container_name: sentry-alice
    image: fantasfived_i
    networks:
      - net-alice
      - net-public
    volumes:
      - ./sentry-alice:/root/.fantasfive

  val-bob:
    command: start
    container_name: val-bob
    image: fantasfived_i
    networks:
      - net-bob
    volumes:
      - ./val-bob:/root/.fantasfive

  sentry-bob:
    command: start
    container_name: sentry-bob
    image: fantasfived_i
    networks:
      - net-bob
      - net-public
    volumes:
      - ./sentry-bob:/root/.fantasfive

  node-carol:
    command: start
    container_name: node-carol
    image: fantasfived_i
    networks:
      - net-public
    ports:
      - 0.0.0.0:26657:26657
      - 0.0.0.0:1317:1317
    volumes:
      - ./node-carol:/root/.fantasfive