apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: node-carol
  name: node-carol
spec:
  ports:
    - name: "26657"
      port: 26657
      targetPort: 26657
    - name: "1317"
      port: 1317
      targetPort: 1317
  selector:
    io.kompose.service: node-carol
status:
  loadBalancer: {}
