apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: node-carol
  name: node-carol
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-carol
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/prod-sim-net-public: "true"
        io.kompose.service: node-carol
    spec:
      containers:
        - args:
            - start
          image: fantasfived_i
          name: node-carol
          ports:
            - containerPort: 26657
              hostIP: 0.0.0.0
              hostPort: 26657
              protocol: TCP
            - containerPort: 1317
              hostIP: 0.0.0.0
              hostPort: 1317
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /root/.fantasfive
              name: node-carol-claim0
      restartPolicy: Always
      volumes:
        - name: node-carol-claim0
          persistentVolumeClaim:
            claimName: node-carol-claim0
status: {}
